### ISSUE TITLE
[07-03-2024] dump cod error：Failed to find pattern Name

### ISSUE THREAD

**Issue by sfw222** [Scobalula/Cordycep#1]
Failed to find pattern Name: ps::CoDMW6Internal::GetXAssetHeaderSize, Signature: 8B CD 48 8B F0 E8 ?? ?? ?? ?? 49 8B ?? 48, Offset: 6

Failed to find pattern Name: ps::CoDMW6Internal::AddAssetOffset, Signature: 48 89 5C 24 28 E8 ?? ?? ?? ?? 48 8B C7 49, Offset: 6

Failed to find pattern Name: ps::CoDMW6Internal::GetXAssetHeaderSize, Signature: E8 ?? ?? ?? ?? B9 95 00 00 00 E8 ?? ?? ?? ?? 44, Offset: 11

-----------------------------------------------------------------
I don't know it's a bug in cordy or my own operator error，I've tried everything I know to dump the cod, but still get this error.

**Comment by schaziobuccia** [comment]
I had the same error today trying to do the sethandler, I think it's a problem after the game update.

**Comment by ItzNyko** [comment]
same issue aswell

**Comment by dest1yo** [comment]
Updated. Replace the config file in `Data\Configs`
[CoDMW6Handler.toml](https://github.com/Scobalula/Cordycep/blob/c4db643d81a6ce3ef59dd3ec08903ae1ea2225bb/build/Data/Configs/Toml/CoDMW6Handler.toml)
