### ISSUE TITLE
Modern Warfare SP error

### ISSUE THREAD

**Issue by JAanusw** [Scobalula/Cordycep#11]
"An internal error has occured while loading the file: Failed to decompress Oodle Data" comes up whenever I try to load SP missions in MW19. And then it just says "error" when i try to extract it in Greyhound.

**Comment by dest1yo** [comment]
You can give more specific loaded fastfile names and part of them doesn't contain the asset data that you need so you can ignore it.

**Comment by JAanusw** [comment]
I'm sorry, could you be more specific I don't quite understand 😭

**Comment by dest1yo** [comment]
> I'm sorry, could you be more specific I don't quite understand 😭

Show me which file loaded with an error message

**Comment by JAanusw** [comment]
![image_2024-08-01_155901171](https://github.com/user-attachments/assets/101c8dd9-f0e2-46d5-91f9-8847504cd6f4)

**Comment by dest1yo** [comment]
> ![image_2024-08-01_155901171](https://github.com/user-attachments/assets/101c8dd9-f0e2-46d5-91f9-8847504cd6f4)
> 

So that's what I said at the beginning means you can ignore it because this srv prefix file is not have any data that you want

**Comment by JAanusw** [comment]
So it doesn't have anything to do with an error coming up when I try to extract on Greyhound?

**Comment by dest1yo** [comment]
> So it doesn't have anything to do with an error coming up when I try to extract on Greyhound?

yes. dont worry about it :)
