### ISSUE TITLE
Failed to load the dump file

### ISSUE THREAD

**Issue by seaofabsu** [Scobalula/Cordycep#13]
Good day sir,

Cordyceps fails to load the dump file and I'm not quite sure what I'm doing wrong.

Please find my logfile attached.

[ 25-11-2024 12-47-28    ] ----------------------------------------------
[ 25-11-2024 12-47-28    ] Cordycep - Fast File Loader
[ 25-11-2024 12-47-28    ] Version: 2.4.1.0
[ 25-11-2024 12-47-28    ] Support: https://github.com/Scobalula/Cordycep
[ 25-11-2024 12-47-28    ] Discord: https://discord.gg/eY2Y5p2PEp
[ 25-11-2024 12-47-28    ] Donate:  https://ko-fi.com/dest1yo
[ 25-11-2024 12-47-28    ] Developed  by Scobalula
[ 25-11-2024 12-47-28    ] Maintained by dest1yo
[ 25-11-2024 12-47-28    ] ----------------------------------------------
[ 25-11-2024 12-47-28    ] Cordycep is initializing, please wait...
[ 25-11-2024 12-47-28    ] Loaded: 9 handlers.
[ 25-11-2024 12-47-28    ] Cordycep is initialized, enjoy! Always make sure to provide log and info when reporting bugs!
[ 25-11-2024 12-47-28    ] Need help or having trouble? Type: "help" to get info or ask for community support in tool support.
[ 25-11-2024 12-48-51    ] Command entered: dump "C:\Program Files (x86)\Call of Duty\_retail_\cod.exe"
[ 25-11-2024 12-48-51    ] Dumping: C:\Program Files (x86)\Call of Duty\_retail_\cod.exe...
[ 25-11-2024 12-48-51    ] Dumping: C:\Program Files (x86)\Call of Duty\_retail_\cod.exe...
[ 25-11-2024 12-48-51    ] Successfully initialized the dumper and Scylla.
[ 25-11-2024 12-48-57    ] Successfully dumped the required data, this can now be used with the title its intended for.
[ 25-11-2024 12-49-05    ] Command entered: help
[ 25-11-2024 12-49-05    ] To use Cordycep, you can simply pass it commands to tell it what to do.
[ 25-11-2024 12-49-05    ] Here's a list of commands:
[ 25-11-2024 12-49-05    ] 	clearflags                       Clears all flags within the handler.
[ 25-11-2024 12-49-05    ] 	deinit                           Unloads all files and deinitializes the current handler.
[ 25-11-2024 12-49-05    ] 	disableverbosity                 Disables verbosity.
[ 25-11-2024 12-49-05    ] 	dump                             Creates a Cordycep-Compatible dump of the provided exe.
[ 25-11-2024 12-49-05    ] 	enableverbosity                  Enables verbosity.
[ 25-11-2024 12-49-05    ] 	explain                          Explains the provided command.
[ 25-11-2024 12-49-05    ] 	help                             Shows the help message.
[ 25-11-2024 12-49-05    ] 	init                             Initializes the current handler with a given game path.
[ 25-11-2024 12-49-05    ] 	listfiles                        Lists all potential files to the log.
[ 25-11-2024 12-49-05    ] 	loadalias                        Loads files from the alias cache with the given name.
[ 25-11-2024 12-49-05    ] 	load                             Loads a file with the given name.
[ 25-11-2024 12-49-05    ] 	loadcommonfiles                  Loads common files for the current handler.
[ 25-11-2024 12-49-05    ] 	loadlist                         Loads files using a list file.
[ 25-11-2024 12-49-05    ] 	dumpaliases                      Dumps all supported items as aliases into a config json.
[ 25-11-2024 12-49-05    ] 	loadwc                           Loads a file using wildcard matching if supported by the handler.
[ 25-11-2024 12-49-05    ] 	removeflag                       Removes the provided flag within the handler.
[ 25-11-2024 12-49-05    ] 	setflag                          Sets the provided flag within the handler.
[ 25-11-2024 12-49-05    ] 	sethandler                       Sets the current handler.
[ 25-11-2024 12-49-05    ] 	setlocaleprefix                  Sets the game specific locale prefix.
[ 25-11-2024 12-49-05    ] 	unloadalias                      Unloads all files potentially loaded by the given alias.
[ 25-11-2024 12-49-05    ] 	unloadall                        Unloads all files, including common files.
[ 25-11-2024 12-49-05    ] 	unloadallnoncommon               Unloads all non-common files.
[ 25-11-2024 12-49-05    ] 	unload                           Unloads a file with the given name.
[ 25-11-2024 12-49-05    ] Need a quick start? To initialize a game: sethandler <Handler Name> init <Game Path> setlocaleprefix <Locale Prefix> loadcommonfiles
[ 25-11-2024 12-49-05    ] For example: sethandler mw4 init "C:\Battlenet\Call of Duty Modern Warfare" setlocaleprefix "english\eng_" loadcommonfiles
[ 25-11-2024 12-49-05    ] To load individual files: load <File Name>, for example: load mp_shipment
[ 25-11-2024 12-49-05    ] To load a list of files: loadlist C:\List.txt
[ 25-11-2024 12-49-05    ] To load files using pattern/wildcards: loadwc <pattern>, for example: loadwc *mpapa5*
[ 25-11-2024 12-49-05    ] To load files using aliases: loadalias <item name>, for example: loadalias "MP-5"
[ 25-11-2024 12-49-05    ] Here's a list of handlers Cordycep currently supports:
[ 25-11-2024 12-49-05    ] 	aw           Call of Duty: Advanced Warfare
[ 25-11-2024 12-49-05    ] 	ghosts       Call of Duty: Ghosts
[ 25-11-2024 12-49-05    ] 	iw           Call of Duty: Infinite Warfare
[ 25-11-2024 12-49-05    ] 	mw2cr        Call of Duty: Modern Warfare 2 Campaign Remastered
[ 25-11-2024 12-49-05    ] 	mw4          Call of Duty: Modern Warfare
[ 25-11-2024 12-49-05    ] 	mw5          Call of Duty: Modern Warfare 2 (2022)
[ 25-11-2024 12-49-05    ] 	mw6          Call of Duty: Modern Warfare 3 (2023)
[ 25-11-2024 12-49-05    ] 	mwr          Call of Duty: Modern Warfare Remastered
[ 25-11-2024 12-49-05    ] 	vg           Call of Duty: Vanguard
[ 25-11-2024 12-49-05    ] When reporting bugs with Cordycep, it is vital you provide a full fog file.
[ 25-11-2024 12-49-05    ] Failure to provide the full log file will result in your bug report being ignored.
[ 25-11-2024 13-10-50    ] Command entered: sethandler mw5 init "C:\Program Files (x86)\Call of Duty" SETLOCALEPREFIX "ENG_" loadcommonfiles
[ 25-11-2024 13-10-50    ] Looking for a handler for: mw5...
[ 25-11-2024 13-10-50    ] Successfully set game handler to: Call of Duty: Modern Warfare 2 (2022)
[ 25-11-2024 13-10-50    ] Attempting to initialize: Call of Duty: Modern Warfare 2 (2022), please wait...
[ 25-11-2024 13-10-50    ] Loaded config: CoDMW5Handler.toml
[ 25-11-2024 13-10-50    ] Loaded config: CoDMW5HandlerBeta.toml
[ 25-11-2024 13-10-50    ] Loaded config: CoDMW5HandlerSP.toml
[ 25-11-2024 13-10-50    ] Successfully opened file system in directory: C:\Program Files (x86)\Call of Duty.
[ 25-11-2024 13-10-50    ] Using file system: CascFileSystem
[ 25-11-2024 13-10-50    ] Failed to load the dump file: Data/Dumps/cod22-cod_dump.exe
[ 25-11-2024 13-10-50    ] Error code: 0x7e
[Log.txt](https://github.com/user-attachments/files/17909024/Log.txt)

**Comment by dest1yo** [comment]
mw5 = mw2022
And you should dump the `cod22-cod.exe`
