### ISSUE TITLE
Can’t pull files I don’t know what I’m doing wrong 

### ISSUE THREAD

**Issue by StealthBomberM13** [Scobalula/Cordycep#2]
![Screenshot_2024-04-29_002247](https://github.com/Scobalula/Cordycep/assets/168480000/9e8bdca6-8149-4e02-855f-44906288a974)

I’ve tried replacing the data file. Didn’t help. I tried restarting my pc. Didn’t help.

**Comment by dest1yo** [comment]
Show ur game path wrote in bat file

**Comment by dest1yo** [comment]
remove the `\_retail_` in ur game path
