### ISSUE TITLE
sigs broken

### ISSUE THREAD

**Issue by Konnie141** [Scobalula/Cordycep#3]
[ 01-05-2024 17-30-39    ] Failed to find pattern Name: ps::CoDMW6Internal::ZoneLoaderFlag, Signature: 40 53 80 3D ?? ?? ?? ?? 00 4C 8D 1D ?? ?? ?? FD, Offset: 4
[ 01-05-2024 17-30-40    ] Need help or having trouble? Type: "help" to get info or ask for community support in tool support.

Could you fix please?

**Comment by dest1yo** [comment]
just download latest version in release channel from my discord server which u can find in project github page
