### ISSUE TITLE
Cordycep not loading the common files

### ISSUE THREAD

**Issue by lewzi** [Scobalula/Cordycep#4]
Cordycep not loading the common files after the recent call of duty mw3 update? any help 
![image](https://github.com/Scobalula/Cordycep/assets/169488721/6b083c09-38f0-4ed8-87e1-53dcb581235d)

**Comment by lewzi** [comment]
it just stays like the above picture for a minute then closes

**Comment by zVISCERAL** [comment]
Make sure to update both, GH and Cordycep. 
Looks like you forgot to update both of them.

**Comment by lewzi** [comment]
I'm too familiar with how to update it could u point me into he right direction 😭

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lewzi** [comment]
> Make sure to update both, GH and Cordycep. Looks like you forgot to update both of them.

how does one update the apps

**Comment by lewzi** [comment]
Hi could u tell me how to update greyhound and cordycep please ?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dest1yo** [comment]
just download latest version in release channel from my discord server which u can find in project github page
