### ISSUE TITLE
Failed to find one or more game patterns.

### ISSUE THREAD

**Issue by Mattia743** [Scobalula/Cordycep#6]
I keep getting the below error with MW6 any suggestions how to fix it?  Running the latest release.

Thought it might be the locale, so I tried the following line with both eng_ and english\eng_ and a few other combinations, but no luck.

sethandler mw6 init "D:\Games\Call of Duty" setlocaleprefix "eng_" loadcommonfiles

![Screenshot-Error](https://github.com/Scobalula/Cordycep/assets/169935234/12aba0d0-ab47-4523-a6d8-7b04dc485525)

Thanks for any help.

**Comment by Gealuvuh** [comment]
This is an issue with initializing, Not the locale
Check your Filepath to make sure it goes to the proper folder,

Read the info given in the **_log.txt_** file in your Cordycep folder.

**Comment by Mattia743** [comment]
The paths are correct.

Here is the error from the log file:
[ 15-05-2024 13-43-43    ] When reporting bugs with Cordycep, it is vital you provide a full fog file.
[ 15-05-2024 13-43-43    ] Failure to provide the full log file will result in your bug report being ignored.
[ 15-05-2024 13-45-15    ] Command entered: sethandler mw6 init "D:\Games\Call of Duty" setlocaleprefix "eng_" loadcommonfiles
[ 15-05-2024 13-45-15    ] Looking for a handler for: mw6...
[ 15-05-2024 13-45-15    ] Successfully set game handler to: Call of Duty: Modern Warfare 3 (2023)
[ 15-05-2024 13-45-15    ] Attempting to initialize: Call of Duty: Modern Warfare 3 (2023), please wait...
[ 15-05-2024 13-45-15    ] Loaded config: CoDMW6Handler.toml
[ 15-05-2024 13-45-15    ] Loaded config: CoDMW6HandlerSP.toml
[ 15-05-2024 13-45-15    ] Successfully opened file system in directory: D:\Games\Call of Duty.
[ 15-05-2024 13-45-15    ] Using file system: CascFileSystem
[ 15-05-2024 13-45-22    ] Failed to find pattern Name: ps::CoDMW6Internal::ZoneLoaderFlag, Signature: 40 53 80 3D ?? ?? ?? ?? 00 4C 8D 1D ?? ?? ?? FD, Offset: 4

**Comment by Gealuvuh** [comment]
Are you using Steam or Battle.net?

A faulty dump causes this issue, 
Please ensure you've checked for updates and played the game for a while before proceeding with any dumps.

**Comment by Mattia743** [comment]
I am using Battle.net.  Ran all the updates before doing a dump.  The re-opened the game a couple of times to the main menu, but did not play.  I will try to run a few games and run a dump again.  Thanks!

**Comment by Gealuvuh** [comment]
If the error persists with the new dump, try swapping your MW6 handler with the attached file.

_**It's formatted in .JSON; however, you'll need to convert it to .TOML since GitHub doesn't support TOML format.**_
[CoDMW6Handler.json](https://github.com/Scobalula/Cordycep/files/15325840/CoDMW6Handler.json)

**Comment by Mattia743** [comment]
Every converter i try to go from JSON to TOML gives me an error when I import the file you provided.

**Comment by Gealuvuh** [comment]
Join the discord and Ping me (Same Username) 
I'll send you the original file

**Comment by Mattia743** [comment]
Nevermind. I just changed the file extension from .json to .toml  I looked at the original and the formatting was the same.

**Comment by Mattia743** [comment]
Sent you a message since we are on a common server on Discord

**Comment by Mattia743** [comment]
Thank you for the info. Got it working!

**Comment by dest1yo** [comment]
just download latest version in release channel from my discord server which u can find in project github page

**Comment by dest1yo** [comment]
just download latest version in release channel from my discord server which u can find in project github page
