### ISSUE TITLE
The handler failed to initialize

### ISSUE THREAD

**Issue by postredaction** [Scobalula/Cordycep#9]
[ 25-06-2024 15-40-08    ] -----------------------
[ 25-06-2024 15-40-08    ] Cordycep - Version: 2.4.0.1
[ 25-06-2024 15-40-08    ] Fast File Loader
[ 25-06-2024 15-40-08    ] Discord: https://discord.gg/eY2Y5p2PEp
[ 25-06-2024 15-40-08    ] Support: https://github.com/Scobalula/Cordycep
[ 25-06-2024 15-40-08    ] Developed by Scobalula
[ 25-06-2024 15-40-08    ] Maintained by dest1yo
[ 25-06-2024 15-40-08    ] -----------------------
[ 25-06-2024 15-40-08    ] Cordycep is initializing, please wait...
[ 25-06-2024 15-40-08    ] Loaded: 8 handlers.
[ 25-06-2024 15-40-08    ] Cordycep is initialized, enjoy! Always make sure to provide log and info when reporting bugs!
[ 25-06-2024 15-40-08    ] Need help or having trouble? Type: "help" to get info or ask for community support in tool support.
[ 25-06-2024 15-40-09    ] Command entered: sethandler mwr init "C:\Program Files (x86)\Steam\steamapps\common\Call of Duty - Modern Warfare Remastered\english" setlocaleprefix "eng_" loadcommonfiles
[ 25-06-2024 15-40-09    ] Looking for a handler for: mwr...
[ 25-06-2024 15-40-09    ] Successfully set game handler to: Call of Duty: Modern Warfare Remastered
[ 25-06-2024 15-40-09    ] Attempting to initialize: Call of Duty: Modern Warfare Remastered, please wait...
[ 25-06-2024 15-40-09    ] Attempting to initialize Call of Duty: Modern Warfare Remastered....
[ 25-06-2024 15-40-09    ] Attempting to open directory: C:\Program Files (x86)\Steam\steamapps\common\Call of Duty - Modern Warfare Remastered\english
[ 25-06-2024 15-40-09    ] Successfully opened directory: C:\Program Files (x86)\Steam\steamapps\common\Call of Duty - Modern Warfare Remastered\english
[ 25-06-2024 15-40-09    ] Failed to locate: IW8::Var0
[ 25-06-2024 15-40-09    ] The handler failed to initialize, the log file has more information on why this happened.
[ 25-06-2024 15-40-09    ] Check the game path provided and ensure you've dumped the game correctly.

**Comment by mjkzy** [comment]
get version 2.4.0.3 found in the Discord server channel at #tool-release

**Comment by dest1yo** [comment]
One obvious problem is that you should specify the root directory of your game instead of the `english` subfolder.
Then you need to make sure there are no problems with the your dumped exe and game files integrity
